### ISSUE TITLE
Refactor: Do we need all the data files for examples?

### ISSUE THREAD

**Issue by migduroli** [jimlutsko/classicalDFT#13]
Having adapted the repo to a new folder structure, we have realised there is a bunch of data files which seem to serve as input for examples. The folder itself is actually a bit heavy for a repository. Thus, a natural question comes up: Do we really need all these files? 
Potential answers:

- Yes: Then, could we try and compress the input data and decompress it just locally when examples are run?

- No: Can we then delete the not needed files and consider compression of the remaining ones in a single file?

**Comment by jimlutsko** [comment]
You mean the directory SS31-Mar-2016?  In my opinion, we could eliminate all except 2 (ss109.05998, ss325.52978) which we could keep for convenience. I could then add a small README explaining where the others can be found (on some website).

**Comment by migduroli** [comment]
Thanks, I will proceed to prepare only the required ones and place the others in a .tar.gz file inside examples. This should considerably reduce the size of the repo and the cloning/pulling times.

**Comment by migduroli** [comment]
I've proceeded according to what we discussed, keeping only the strictly needed files without compressing. The remaining files are under `data.tar.gz`. Thus, I'm closing this issue.
