### ISSUE TITLE
Refactor: Potential1 into Physics/Potentials/Intermolecular

### ISSUE THREAD

**Issue by migduroli** [jimlutsko/classicalDFT#24]
As mentioned in issue #15 the refactoring of `classicalDFT` will end up with a new folder structure which aims at better representing the functional modules already existing. One of such modules is the one devoted to the implementation of interaction potentials. And one of such functionalities implemented in this regard is encapsulated in the class `Potential1.h`, within `legacy_lib`. The class contains a base class which is then used to build (via inheritance) some widely-known potentials, namely: `LH` (Lennard-Jones), `tWF` (ten Wolde-Frenkel) and `WHDF` (Wang-Hinestrosa-Dobnikar-Frenkel).

The goal of this issue is not only moving the implementation given in `Potential1.h` into the module `Physics/Potentials/Interparticle`, but also carrying out a proper refactor. This will require re-factoring of the following classes and methods:

- [x] Potential1 => refactor to `Potential`
  - [x] Cttor and Dttor => refactor to `Potential`
  - [x] getHardCore => refactor to `FindHardCoreDiameter`
  - [x] getRcut => refactor to `r_cutoff`
  - [x] getR0 => refactor to `r_zero`
  - [x] getRmin => refactor to `FindRMin`
  - [x] set_WCA_limit => refactor to `SetWCALimit`
  - [x] setBH => refactor to `SetBHPerturbation`
  - [x] V => refactor to `v_potential`
  - [x] V2 => refactor to `v_potential_r2`
  - [x] Watt => refactor to `w_attractive`
  - [x] Watt2 => refactor to `w_attractive_r2`
  - [x] V0 =>refactor to `w_repulsive`
  - [x] getHSD => refactor to `FindHardSphereDiameter`
  - [x] getVDW_Parameter => refactor to `ComputeVanDerWaalsIntegral`
  - [x] getIdentifier => refactor `identifier`
  - [x] vr => refactor `vr_`
  - [x] vr2 => refactor `vr2_`
  - [x] serialize
- [x] LJ => refactor to `LennardJones`
  - [x] getRmin => refactor to `FindRMin`
  - [x] getHardCore => refactor to `FindHardCoreDiameter`
  - [x] getIdentifier => refactor `identifier`
  - [x] vr => refactor `vr_`
  - [x] vr2 => refactor `vr2_`
  - [x] serialize
- [x] tWF => refactor to `tenWoldeFrenkel`
  - [x] getRmin => refactor to `FindRMin`
  - [x] getHardCore => refactor to `FindHardCoreDiameter`
  - [x] getIdentifier => refactor `identifier`
  - [x] vr => refactor `vr_`
  - [x] vr2 => refactor `vr2_`
  - [x] serialize
- [x] WHDF => refactor to `WangRamirezDobnikarFrenkel`
  - [x] getRmin => refactor to `FindRMin`
  - [x] getHardCore => refactor to `FindHardCoreDiameter`
  - [x] getIdentifier => refactor `identifier`
  - [x] vr => refactor `vr_`
  - [x] vr2 => refactor `vr2_`
  - [x] serialize

**Comment by jimlutsko** [comment]
Please use this opportunity to rename Potential1 to something more natural (Potential?). Obviously, there was once a "Potential" class and this one replaced it at some point.
